// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_DoList_AspMVC.Data;

#nullable disable

namespace To_DoList_AspMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004184140_crateDBOne")]
    partial class crateDBOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("To_DoList_AspMVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tasks related to your job or career",
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Personal goals and errands",
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fitness, exercise, and wellness tasks",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Assignments, courses, and study plans",
                            Name = "Study"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Grocery or online shopping lists",
                            Name = "Shopping"
                        });
                });

            modelBuilder.Entity("To_DoList_AspMVC.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("To_DoList_AspMVC.Models.MyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClientId");

                    b.ToTable("MyTask");
                });

            modelBuilder.Entity("To_DoList_AspMVC.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_en")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country_code = "SA",
                            Name_ar = "السعودية",
                            Name_en = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 2,
                            Country_code = "EG",
                            Name_ar = "مصر",
                            Name_en = "Egypt"
                        },
                        new
                        {
                            Id = 3,
                            Country_code = "JO",
                            Name_ar = "الأردن",
                            Name_en = "Jordan"
                        },
                        new
                        {
                            Id = 4,
                            Country_code = "KW",
                            Name_ar = "الكويت",
                            Name_en = "Kuwait"
                        },
                        new
                        {
                            Id = 5,
                            Country_code = "AE",
                            Name_ar = "الإمارات",
                            Name_en = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 6,
                            Country_code = "BH",
                            Name_ar = "البحرين",
                            Name_en = "Bahrain"
                        },
                        new
                        {
                            Id = 7,
                            Country_code = "QA",
                            Name_ar = "قطر",
                            Name_en = "Qatar"
                        },
                        new
                        {
                            Id = 8,
                            Country_code = "OM",
                            Name_ar = "عمان",
                            Name_en = "Oman"
                        });
                });

            modelBuilder.Entity("To_DoList_AspMVC.Models.Client", b =>
                {
                    b.HasOne("To_DoList_AspMVC.Models.Nationality", "Nationality")
                        .WithMany("Clients")
                        .HasForeignKey("NationalityId");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("To_DoList_AspMVC.Models.MyTask", b =>
                {
                    b.HasOne("To_DoList_AspMVC.Models.Category", "Category")
                        .WithMany("TodoTasks")
                        .HasForeignKey("CategoryId");

                    b.HasOne("To_DoList_AspMVC.Models.Client", "Client")
                        .WithMany("MyTasks")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("To_DoList_AspMVC.Models.Category", b =>
                {
                    b.Navigation("TodoTasks");
                });

            modelBuilder.Entity("To_DoList_AspMVC.Models.Client", b =>
                {
                    b.Navigation("MyTasks");
                });

            modelBuilder.Entity("To_DoList_AspMVC.Models.Nationality", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
